[project]
name = "ai-developer-handbook"
version = "0.1.0"
description = "Panduan best practice building App."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "mkdocs-mermaid2-plugin>=1.1.1",
    "pymdown-extensions>=10.8",
]
