openapi: 3.1.0
info:
  title: Example API
  version: "0.1.0"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /healthz:
    get:
      responses:
        "200":
          description: OK
  /users:
    get:
      security: [ { bearerAuth: [] } ]
      responses: { "200": { description: OK } }
    post:
      security: [ { bearerAuth: [] } ]
      responses: { "201": { description: Created } }
security:
  - bearerAuth: []
